## Introduction to Python
In this module, you'll get an introduction to Python coding in Jupyterhub Notebook. It'll be mostly about navigating your way around this "ecosystem." The context will be something you're hopefully a little familiar with -- the ideal gas law.

### Markdown cells and code cells
The text you're reading is enclosed in a box called a "markdown cell." Markdown cells have text, equations, etc. Most markdown cells you'll be working with will be read-only, meaning you're not supposed to change them. You can execute a markdown cell by pressing the return key while holding down shift. Try it now! You'll see that not much seems to have happened (because this is a read-only cell). As we go along, however, you'll see that some markdown cells are set aside for you to respond to a prompt of some kind -- usually to reflect or analyze something you've just done or seen. You execute those in the same way: after editing, you'll press return while holding down shift.

A second type of cell is called a "code cell." Code cells do all the computing work in a Python Notebook. You'll also be executing code cells, in the same way (shift-return). But more on that later.

### E-format convention for scientific notation
When working in a computational environment like Python, it's important to get used to entering numbers in scientific notation using the *e-format convention*. For example, Boltzmann's constant, $k_B$, might be written $1.3806×10^{-23}$ (in units $m^2 \ kg \ s^{-2} \ K^{-1}$), but in Python you would enter it as "1.3806e-23". The "e" can be "E", by the way; the e-format convention is not case-sensitive.

### Unit conversions and coherent unit systems
The foregoing example brings up a key point: unless a number is dimensionless (like $\pi$), we need to pay attention to its *units*. Units are always a bit of a bother in ... all of pchem ... because one is frequently faced with having to do unit conversions. Fortunately, Python has a nice package, call *pint*. *pint*  has a ton of built-in conversions, it knows how to convert from one to another, and it's pretty intuitive (more on this below). If you've wrestled in the past with unit conversions, this might seem just a bit too easy. But mainly it removes the drudgery of unit conversions; you still have to know what you're doing.  

Another thing about units, is that they're not as arbitrary as you might think. Units come in collections, called *unit systems*. For example, in the SI unit system (a favorite among thermodynamicists), the unit for time is seconds, for distance it's meters, etc. Moreover, if a unit system been designed properly, it has a property called *coherence*. Lots of calculations become simplified when a unit system has coherence. For example, say you are working in the SI unit system, and you have calculated an acceleration using $a=F/m$. You *could* go through the bother of unit analysis of $F$ and $a$ to figure out the units of $a$. OR you could recognize that SI is a coherent unit system, so you are *guaranteed* that if $F$ and $a$ are SI, then $a$ is *guaranteed* to be $m/s^2$ (and not $miles/hour^2$ or something else). Yes, guaranteed! 

You can check out https://en.wikipedia.org/wiki/Coherence_(units_of_measurement) for a complete definition of coherence, https://en.wikipedia.org/wiki/International_System_of_Units for details about the SI system, and http://pint.readthedocs.org/en/latest/nonmult.html for a description of *pint*. The point for now is, the combination of unit coherenence and *pint* is pretty powerful, and this module will get you grounded in the basics. 

### Named variables
Trying to not overload you too much in this introduction, but one more idea that will help as you go through this module is that Python has a built-in way of storing quantities, called *named variables*. That means if you use Eqs. (1) and (2) to calculate two pressures, and you give these pressures different names (like "P" and "Pvdw"), then Python will keep those values for you to use later. This might not sound like much, but when you're faced with the complex, multi-step calculations typical of thermodynamcis, it's very handy -- essential, really. 

### Chemical context - ideal gases and van der Waals gases

One way of predicting the pressure of a gas is to use what's called the *Ideal Gas Law*,

$$
P = {{n R T} \over V} \ \ \ (1)
$$

where $P$ is the pressure of a gas, $V$ is the volume of the container it's in, $n$ is the amount of gas in that container, and $R$ is called the *Universal Gas Constant*, $8.314 {{J \over {mol \ K}}}$. You might be familiar with Eq. (1) in different forms, like $PV = n R T$, $n = {{PV} \over {RT}}$, etc., but of course those are just different algebraic expressions of the same relationship. 

Another prediction is given by the *van der Waals* (vdw) equation, 

$$
P = {{n R T} \over {V - nb}} - {{n^2 a} \over V^2}  \ \ \ (2)
$$

where $a$ and $b$ are called van der Waals constants. These constants -- they are specific to each gas -- are tabulated in various places, inluding your text, and at https://en.wikipedia.org/wiki/Van_der_Waals_constants_(data_page). 

### Comparison metrics
So, how good are these formulas? (Chemists tend to ask this about *any* "law", for that matter; we're a suspicious lot.) The best comparison, of course, would be to compare the pressure predicted by Eq. (1) to an experimental value, but that's not always very convenient. 

Regarding that question about the accuracy of the ideal gas law, there are several options we can imagine. 
- We could just inspect the difference, $P_{vdw} - P_{ideal}$ (or $P_{ideal} - P_{vdw}$).  

- The percent difference, $({P_{vdw}}/{P_{ideal}}-1)\times 100$, etc.

- The ratio, $P_{vdw}/P_{ideal}$, etc. In that case, of course, you'd be interested in deviations from one.  

For this module, we'll be evaluating these differences at more or less room conditions, and for a particular gas (Argon), but later we'll be exploring how that varies from gas to gas, and why.


### Learning goals
The main learning goals of this exercise can be phrased follows. 
1. I can create named variables in Python.
1. I can enter numbers in scientific notation using the E-format convention.
1. I'm familiar with key aspects of *pint*, e.g., specifying quantities with units, and making persistent or on-the-fly conversions.
1. I'm familiar with common pressure units (atm, bar, pascal, and torr), and can sort them in order of how big they are.
1. I can carry out algebraic and numerical calculations involving the ideal gas law, and evaluate the error in it relative to more accurate formulations, such as vdw's equation.

The next cell -- like all cells in a Python Notebook -- is executed by clicking in the cell and holding down the "shift" button as you press enter. Do that now.

In [3]:
# Import resources stored in the Pchem Library
%run ../PchemLibrary/ImportResources.ipynb

### Defining constants
The universal gas constant is defined in the following cell, in SI units. Then it's converted to base SI units. These two are numerically the same, but in the second case the derived unit "Joule" has been broken down into its base SI units.

In [4]:
R = AssignQuantity(8.314,"J/(mol K)")
print(R)
R.ito_base_units()
print(R)

8.314 joule / kelvin / mole
8.314 kilogram * meter ** 2 / kelvin / mole / second ** 2


### Pause for analysis
Study these results for a moment. The value of $R$ is the same in $J \over {mol \ K}$ as it is in $kg \ m^2 \over {mol \ K \ s^2}$.  So that means the base unit of a "Joule" must be $kg \ m^2 \over s^2$, right? Double-check that this is correct by inspecting the "SI derived units with special names and symbols" table at https://en.wikipedia.org/wiki/International_System_of_Units.

Another point about what you just did: the ".ito_base_units" made it so that R's units will be $kg \ m^2 \over {mol \ K \ s^2}$ from now on; we say that ".ito ..." is a *persistent* conversion. You'll see below that there are ways to carry out more fleeting conversions too, which is sometimes handy.

### Your turn
1. Using *pint*, specify R as $0.082057 {{\ L \ atm} \over {mol \ K}}$.
1. Convert that value of R to $J \over {mol \ K}$. 
1. Print both values

In [5]:
### BEGIN SOLUTION
R = AssignQuantity(0.082057,"L atm /(mol K)")
print(R)
R.ito("J /mol /K")
print(R)
### END SOLUTION

0.082057 liter * standard_atmosphere / kelvin / mole
8.314425525000003 joule / kelvin / mole


### On-the-fly unit conversion
The code below highlights the fact that we can also do unit conversions "on the fly", using ".to" instead of ".ito").

In [6]:
# This prints R from the last cell
print(R)

# This converts R back to L-atm units only for as long as it takes to print it
print(R.to("L atm/(mol K)"))

# R is unchanged
print(R)

8.314425525000003 joule / kelvin / mole
0.08205700000000002 liter * standard_atmosphere / kelvin / mole
8.314425525000003 joule / kelvin / mole


### Your turn
In the cell below,
1. Define Boltzmann's constant, $1.3806×10^{-23} m^2 \ kg \ s^{-2} \ K^{-1}$, using the E-format convention (i.e., "1.3806e-23"). Name the variable "kB". 
1. Do a persistent unit conversion to "J/K". The result should be numerically the same, since $1 \ J = 1 \ {kg \ m^2 \over s^2 } $, as you already figured out.
1. Do an on-the-fly conversion to print the value of kB in units "kiloJ/K".

In [7]:
### BEGIN SOLUTION
kB = AssignQuantity(1.3806e-23,"m^2 kg s^-2 K^-1")
print(kB)

kB.ito("J/K")
print(kB)

print(kB.to("kiloJ/K"))
### END SOLUTION

1.3806e-23 kilogram * meter ** 2 / kelvin / second ** 2
1.3806e-23 joule / kelvin
1.3806e-26 kilojoule / kelvin


### Ideal gas law calculations

The next cell uses the ideal gas law, Eq. (1). 

In [8]:
P_ideal = AssignQuantity(1,"atm"); print(P_ideal)
V = AssignQuantity(250,"ml"); print(V)
T = AssignQuantity(298,"K"); print(T)

n = P_ideal*V/(R*T); print(n)
n.ito_base_units(); print(n)

1 standard_atmosphere
250 milliliter
298 kelvin
0.10090007685728163 milliliter * mole * standard_atmosphere / joule
0.010223700287564062 mole


### Pause for analysis
If you look carefully at cell, you'll notice that we've introduced a new syntax option: the semicolon. A semicolon lets you put two Python commands on the same line. For example, instead of 

    P_ideal = AssignQuantity(1,"atm")
    print(P_ideal)

we've elected to write

    P_ideal = AssignQuantity(1,"atm"); print(P_ideal)

These do exactly the same thing, it just makes for more compact code (which some people like).

### Your turn
In the next cell, 
1. Replicating the syntax just described (i.e., with the semicolon), define variables $n=0.01 \ mol$, $V=250 \ mL$, and $T=298 \ K$.
1. Calculate the gas pressure based on the ideal gas law -- and name the new pressure "P_ideal". 
1. Print P_ideal -- you'll see that the units are nothing you've seen before. That's because we have a unit mismatch: the volume was given in mL, but R was in L-atm/mol/K. Not to dismay, however: see the next step.
1. Do four on-the-fly conversions to atm, bar, pascals, and torr, printing the results as you go. Your resulting pressure in atm in should be pretty close to 1  -- just a little smaller because you're using 0.01 moles instead of 0.0102 moles. The others might be bigger or smaller. 

Then 

5. Rearrange the order of your four on-the-fly print statements (atm, bar, pascals, and torr -- leave out the wonky "joule / milliliter" result) so that the numbers are numerically smallest to largest. 

In [9]:
### BEGIN SOLUTION

n = AssignQuantity(0.01,"mol"); print(n)
V = AssignQuantity(250,"ml"); print(V)
T = AssignQuantity(298,"K"); print(T)

P_ideal = n*R*T/V
print(P_ideal)
print(P_ideal.to("atm"))
print(P_ideal.to("bar"))
print(P_ideal.to("torr"))
print(P_ideal.to("pascal"))

### END SOLUTION

0.01 mole
250 milliliter
298 kelvin
0.09910795225800002 joule / milliliter
0.9781194400000002 standard_atmosphere
0.9910795225800002 bar
743.3707744000001 torr
99107.952258 pascal


### Pause for analysis
Based on what you you just got, you should be able to tell which pressure unit is the *tiniest*, and which is the *biggest*. Then enter your responses to these three prompts in the cell below:

1. The tiniest unit of pressure of these four is: 

2. The biggest unit of pressure of these four is: 

3. 1 atm is almost the same as 1 bar, but is a pressure of 1 atm bigger than 1 bar, or smaller? 

### Three steps for refreshing and saving your code
It's good practice to, periodically, re-run the notebook up to here, from the beginning, refreshing all the variables:

1. Use the dropdown menu Kernel/Restart
2. Use the dropdown menu Cell/Run All Above

Try this now! Assuming all goes well, take this additional step:

3. Under the "File" dropdown menu item in the upper left is a disk icon. Press it now to save your work (and do it again every few minutes!)

### The flexibility of *pint*
Turns out, *pint* offers remarkable flexibility in specifying units, as demonstrated in the cell below.

In [10]:
a = AssignQuantity(1.355,'L^2 bar mol^-2'); print(a)
a = AssignQuantity(1.355,'L**2 bar mol**-2'); print(a)

1.355 bar * liter ** 2 / mole ** 2
1.355 bar * liter ** 2 / mole ** 2


### A difference between *pint* and *Python*
While *pint* recognizes ^ and \** to mean the same thing -- raising a quantity to a power -- *Python* recognizes only latter. That means it's fine to say either of these:

    Volume = 22.4*ureg.m**3     # OK syntax
    Area = 3**2                 # OK syntax
    
but Python will throw an error if you try this:

    Volume = 22.4*ureg.m^3      # bad syntax
    Area = 3^2                  # bad syntax


### Your challenge
Your challenge for the rest of this exercise is to evaluate the error in approximating the pressure of Argon gas using the ideal gas law, considering the "truth" as being what vdw's equation yields for the pressure. Specifically,

1. Find vdw constants $a$ and $b$ for Argon gas, noting the units.
1. Use  Eq. (2) to calculate the pressure of Argon gas under the same conditions as previously (0.01 mol in a 250 mL flask, etc). Store this result as the variable "P_vdw" so you don't clobber the value stored in P_ideal.
1. Print the van der Waals pressure and the ideal gas law pressure in the same units (your choice!).
1. Evaluate the difference between an ideal gas law and a vdw gas using one of the metrics mentioned above, and print that result too.

In [11]:
### BEGIN SOLUTION
a = AssignQuantity(1.355,'L^2 bar / mol^2'); print(a)
b = AssignQuantity(0.032,'L /mol'); print(b)
P_vdw = n*R*T/(V-n*b)-n**2*a/V**2

print("vdw gas in the units used:", P_vdw)
print("vdw gas converted to atm:", P_vdw.to("atm"))
print("ideal gas converted to atm:", P_ideal.to("atm"))

error = P_vdw.to("pascal")-P_ideal.to("pascal")
print("difference:", error)

error = (P_vdw.to("atm")/P_ideal.to("atm")-1)*100
print("%difference:", error)

error = P_vdw.to("atm")/P_ideal.to("atm")
print("ratio:", error)

### END SOLUTION

1.355 bar * liter ** 2 / mole ** 2
0.032 liter / mole
vdw gas in the units used: 0.09901817302347006 joule / milliliter
vdw gas converted to atm: 0.9772333878457445 standard_atmosphere
ideal gas converted to atm: 0.9781194400000002 standard_atmosphere
difference: -89.7792345299531 pascal
%difference: -0.09058731664259856 dimensionless
ratio: 0.999094126833574 dimensionless


### One last refresh and save
We're at the end of the notebook. You should repeat the "Three steps for refreshing and saving your code" you did before. Instead of using the dropdown menu "Cell/Run All Above", however, you may as well use "Cell/Run All".

### Validating
This step will help ensure that you didn't miss something (although it's not a guarantee). Find the "Validate" button and press it. If there are any errors or warnings, fix them.

### Three steps for finishing up
Assuming all this has gone smoothly, there will be three more steps (but read this carefully before carrying them out):
1. Close this notebook using the "File/Close and Halt" dropdown menu
1. Using the Assignments tab, submit this notebook
1. Press the Logout tab of the Home Page